### ISSUE TITLE
how many colors can detect? 

### ISSUE THREAD

**Issue by xuweidongkobe** [MarvinKweyu/ColorDetect#60]
Hi ,thanks for your work, it helps me a lot. The question is how many colors can detect, can you give me a list ?

**Comment by MarvinKweyu** [comment]
Hello there @xuweidongkobe . Following the documentation [Example](https://colordetect.readthedocs.io/en/master/colordetect.html#example-1), ColorDetect takes a default of 5 most dominant colors. If you want more, just parse the argument to the relevant method. The limit of this is up to you.
