### ISSUE TITLE
get_color_count() failed when having colors with equal percentage

### ISSUE THREAD

**Issue by whzzt** [MarvinKweyu/ColorDetect#61]
In `colordetect/color_detect.py`, line 258, the `sorted` function will raise an error when two values in `hist` are equal because the result of comparing two `np.ndarray` is used as a value.

**Comment by MarvinKweyu** [comment]
@whzzt Great note there.

**Comment by whzzt** [comment]
> @whzzt Great note there. I can check on that. Do you have a sample image with you for the tests and subsequent fix?

I cannot find it now, but I guess there will be one if you test it on a cropped region of a video.

**Comment by MarvinKweyu** [comment]
closed by #65
